### PR TITLE
Paper edits for JOSS

### PR DESCRIPTION
**Pull request by theorashid**
## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [x] Other (please describe): paper

## What is the current behavior?

Issue Number: N/A

## Other information

Hey Thomas and Daniel,

This is for openjournals/joss-reviews#4455. There was a broken reference and a typo. Also, you mentioned you wanted the title changed to GPJax: A __didactic__ Gaussian Process framework in Jax. Now is your chance to add it (although personally I think "didactic" only makes the title confusing).

A couple of other points, which I'm happy for an open discussion:
- Are there no GPs packages in R? How do R users get by? 
- Is it worth mentioning that some PPLs have submodules for GPs which are commonly used, e.g pymc. Feel free to convince me these are really limited compared to the purpose-built libraries
- Is it worth mentioning the other jax-based GP packages: [tinygp](https://tinygp.readthedocs.io/en/stable/motivation.html) and [bayesnewton](https://github.com/AaltoML/BayesNewton/tree/main/bayesnewton). bayesnewton has also been used by the Aalto team for graph GPs (in jax). tinygp interests me because it integrates with numpyro, which I find much better than tfp.

Best,

Theo

### CODE REVIEW

**Comment by thomaspinder** [comment]
Hi @theorashid. I'm unsure if you can see my update to your PR, but I have responded to your comments and updated the paper accordingly [here](https://github.com/thomaspinder/GPJax/commit/9bf9d12ee37b760518c3c6e75a88b20382049e6e).

**Comment by theorashid** [comment]
Great. Are you able to merge these to master? Then I will remake the pdf using the bot and read through it again

**Comment by thomaspinder** [comment]
> Great. Are you able to merge these to master? Then I will remake the pdf using the bot and read through it again

Done!

**Comment by theorashid** [comment]
It doesn't seem to have merged your updates

**Comment by thomaspinder** [comment]
My bad. Should be merged now.

**Pull request merged**
